name: Flutter Debug APK Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      # Optional: Uncomment if you have tests
      # - name: Run tests
      #   run: flutter test

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Show APK files
        run: ls -R build/app/outputs/flutter-apk/

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
