name: Flutter Debug APK Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # Use desired Flutter version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test

      - name: Build Android debug APK
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
